# Site settings
title: "HI-ARC"
fulltitle: "홍익대학교 알고리즘 학회<br>HI-ARC 공식블로그"
tagline: ""
url: "http://hi-arc.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

color-theme: "pink"

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: "hongikuniv.hiarc"
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
phone: "010-1234-5678" # This is my real number. You should text me.
email: "hello@gmail.com" # This is my real email address. Please don't email me.
apply-form: ""

# Category
collections:
  - sections

# Use this for production
#sass:
#  style: compressed

exclude: [.scss, .gitignore, .travis.ci, Gemfile, Gemfile.lock, README.md, node_modules, gruntfile.js, package.json]
